[package]
name = "toml-edit-js"
version = "0.5.0"
edition = "2024"
authors = ["rainbowatcher <rainobw-w@qq.com>"]
description = "Edit TOML files in JavaScript"
repository = "https://github.com/rainbowatcher/toml-edit-js"
license = "MIT"
readme = "README.md"
categories = ["wasm"]
keywords = ["wasm", "toml", "edit", "javascript"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
toml_edit = { version = "0.23.1" }
wasm-bindgen = "0.2.100"
console_error_panic_hook = "0.1.7"
web-sys = { version = "0.3.77", features = ["console"] }
once_cell = "1.21.3"

[dev-dependencies]
indoc = "2.0.6"
wasm-bindgen-test = "0.3.50"

[profile.release]
lto = true

[package.metadata.wasm-pack.profile.release]
debug-js-glue = false
demangle-name-section = true
dwarf-debug-info = false
omit-default-module-path = false
wasm-opt = [
    # Optimize level 4
    "-O4",
    # Run passes to convergence, continuing while binary size decreases
    "--converge",
    "--strip-debug",
    "--strip-dwarf",
    # flattens out code, removing nesting
    # "--flatten",
    # inline small functions
    "--inlining",
    # removes unreachable code
    "--dce",
    # Grand Unified Flow Analysis
    "--gufa",
]
