name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  base:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [18, 20]
        include:
          - os: macos-latest
            node_version: 20
          - os: windows-latest
            node_version: 20
      fail-fast: false

    runs-on: ${{ matrix.os }}

    name: "node-${{ matrix.node_version }}, ${{ matrix.os }}"

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Install
        run: pnpm i --frozen-lockfile

      - name: wasmup install
        run: pnpm exec wasmup install

      - name: Build
        run: pnpm build

      - name: Type Check
        run: pnpm typecheck

      - name: Test
        run: pnpm test

      - name: Lint
        run: pnpm lint
